### ISSUE TITLE
Will node-hnapi continue to be supported?

### ISSUE THREAD

**Issue by mbmccormick** [cheeaun/node-hnapi#12]
With the official Hacker News API rolling out, are there plans to continue supporting node-hnapi? I use this API for my Windows Phone app (http://github.com/mbmccormick/HackerNews) and I'm trying to decide if I am safe continuing to use this project or if I need to start migrating over to the official API. Thanks! :smile:

**Comment by cheeaun** [comment]
Closing issue, since uh, I've answered your question :smile:
