### ISSUE TITLE
Missing `time` and empty `time_ago` data in some paths

### ISSUE THREAD

**Issue by ryanss** [cheeaun/node-hnapi#15]
The items in the following new base paths are missing the `time` key and have an empty `time_ago` value:

* /best
* /active
* /noobstories

**Comment by cheeaun** [comment]
Fixed in 4cd42c22cc1a5aa5b92e010702259a06f789aa69

Note: These three endpoints are **scraped** from HN web site and **not** from the official API. So, there's `time_ago` key but **no** `time` key with Unix timestamp value since there's... none on the site.

**Comment by ryanss** [comment]
Great, thank you! `time_ago` was the data I needed, I just mentioned `time` because I thought they might be related.
