### ISSUE TITLE
Difference between news and news2

### ISSUE THREAD

**Issue by amilajack** [cheeaun/node-hnapi#20]
Dont this this is clear in the docs.

<img width="529" alt="screen shot 2016-06-15 at 11 25 28 am" src="https://cloud.githubusercontent.com/assets/6374832/16092268/eee45846-32eb-11e6-9ab3-bfa5319d4f2f.png">

What is the difference between the two?

**Comment by amilajack** [comment]
Oh wait, never mind. I got it now. It would be much more intuitive to use some kind of pagination method.

```
http://node-hnapi.herokuapp.com/news?page=2
```

**Comment by cheeaun** [comment]
@amilajack `page` param works too actually. `news2` was more of a legacy thing when HN didn't support pagination last time.

**Comment by amilajack** [comment]
I edited the wiki to reflect this. Are there any other parameters that are not explicitly mentioned in the docs?

**Comment by cheeaun** [comment]
@amilajack not that I could think of. One of the reasons I don't document `page` is also to prevent abuse as I would encourage people to use the official API instead of this unofficial API :)
