### ISSUE TITLE
/news and /jobs returning error

### ISSUE THREAD

**Issue by leonsenft** [cheeaun/node-hnapi#28]
Currently [/news](http://api.hackerwebapp.com/news) and [/jobs](http://api.hackerwebapp.com/jobs) are returning an error:

```json
{"error":"Cannot read property 'replace' of undefined"}
```

**Comment by leonsenft** [comment]
This is no longer occurring, but I'll leave this open in case you'd like to investigate the cause.

**Comment by cheeaun** [comment]
@leonsenft hey thanks! I just looked at the logs and the only thing I see are timeout errors from fetching the Firebase HN API 😓 I suspect it's an issue there but I'll keep a look out.

Closing for now. Feel free to open another issue if this happens again 💪
