### ISSUE TITLE
504 when fetching comment

### ISSUE THREAD

**Issue by devnoname120** [cheeaun/node-hnapi#32]
Tests:

- https://api.hackerwebapp.com/item/3338903
![image](https://user-images.githubusercontent.com/2824100/55684371-516c1300-594a-11e9-81a4-c97077c23e24.png)

- http://node-hnapi.herokuapp.com/item/3338903
Empty page, `504` returned.

Proof that this id is valid: https://news.ycombinator.com/item?id=3338903

Might be related to this: https://github.com/cheeaun/node-hnapi/issues/18#issuecomment-174439150

**Comment by cheeaun** [comment]
Oh, hmm. First, this API doesn't work for comment-type IDs. Or at least I didn't test and not planning to support it. For HN's official API, the ID is an **Item ID**, which can be a story or comment `type`.

So the ID is valid, just that `node-hnapi` is not supporting comment-type ID.

**Comment by devnoname120** [comment]
Ah thanks, in this case I'm updating the documentation because it's incorrect: https://github.com/cheeaun/node-hnapi/wiki/API-Documentation#get-itemid

**Comment by cheeaun** [comment]
@devnoname120 thanks! sorry for the confusion 😃
