### ISSUE TITLE
Heroku Application error

### ISSUE THREAD

**Issue by edjw** [cheeaun/node-hnapi#41]
API seems to be down thanks to something in Heroku

https://api.hackerwebapp.com

**Comment by mblode** [comment]
Most likely caused because [Heroku will delete all free dbs and shut down all free dynos Monday](https://news.ycombinator.com/item?id=33755651)

**Comment by vinc** [comment]
Indeed.. I've been using the API for years at https://news.vinc.cc without any issues and it'd be sad to see it going dark.

**Comment by cheeaun** [comment]
Hey all sorry for this very, very late response. I've subscribed to the eco dynos plan and it should be working now 🙇

**Comment by vinc** [comment]
Thanks! :+1:

**Comment by edjw** [comment]
Thanks very much!
